import './globals.css'
import type { Metadata } from 'next'
import { FinanceProvide } from '@/context/finance-expenses'


export const metadata: Metadata = {
  title: 'Nextjs Form',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <FinanceProvide>
        <body>{children}</body>
      </FinanceProvide>
    </html>
  )
}
